<a href="https://colab.research.google.com/github/priyankavarshneyyy/eightthSEM/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ar=np.random.randint(1,10,10)
ar

array([3, 1, 9, 8, 3, 6, 4, 5, 7, 3])

In [ ]:
print(ar.max())
print(ar.min())

9
1


In [ ]:
a=np.random.randint(1,100,56)
a

array([85, 13, 43, 47, 80, 62, 81, 42, 46, 51, 56, 63, 88, 31, 98, 34, 11,
       87, 61, 62, 83, 62,  5, 38, 23, 23, 10, 73, 89, 11, 33, 76, 97,  9,
       98, 81, 24, 31, 80,  9, 37, 62, 45, 84, 55, 60,  4, 79, 37, 24, 13,
       34, 85, 80, 14, 85])

In [ ]:
a.reshape(7,8)

array([[85, 13, 43, 47, 80, 62, 81, 42],
       [46, 51, 56, 63, 88, 31, 98, 34],
       [11, 87, 61, 62, 83, 62,  5, 38],
       [23, 23, 10, 73, 89, 11, 33, 76],
       [97,  9, 98, 81, 24, 31, 80,  9],
       [37, 62, 45, 84, 55, 60,  4, 79],
       [37, 24, 13, 34, 85, 80, 14, 85]])

In [ ]:
a.reshape(4,14)

array([[85, 13, 43, 47, 80, 62, 81, 42, 46, 51, 56, 63, 88, 31],
       [98, 34, 11, 87, 61, 62, 83, 62,  5, 38, 23, 23, 10, 73],
       [89, 11, 33, 76, 97,  9, 98, 81, 24, 31, 80,  9, 37, 62],
       [45, 84, 55, 60,  4, 79, 37, 24, 13, 34, 85, 80, 14, 85]])

In [ ]:
df=pd.read_csv("students.csv")
df.head(5)

,RollNo,Name,Age,Marks,Department
0,1,Student1,18,65,Computer Science
1,2,Student2,19,72,Information Technology
2,3,Student3,20,81,Data Science
3,4,Student4,21,90,Computer Science
4,5,Student5,22,77,Information Technology


In [ ]:
df.head()

,RollNo,Name,Age,Marks,Department
0,1,Student1,18,65,Computer Science
1,2,Student2,19,72,Information Technology
2,3,Student3,20,81,Data Science
3,4,Student4,21,90,Computer Science
4,5,Student5,22,77,Information Technology


In [ ]:
df.tail()

,RollNo,Name,Age,Marks,Department
95,96,Student96,18,69,Data Science
96,97,Student97,19,82,Computer Science
97,98,Student98,20,77,Information Technology
98,99,Student99,21,88,Data Science
99,100,Student100,22,90,Computer Science


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   RollNo      100 non-null    int64 
 1   Name        100 non-null    object
 2   Age         100 non-null    int64 
 3   Marks       100 non-null    int64 
 4   Department  100 non-null    object
dtypes: int64(3), object(2)
memory usage: 4.0+ KB


In [ ]:
import pandas as pd
import numpy as np
np.random.seed(1)
data = {
    "Age": np.random.randint(25, 65, 100),
    "BMI": np.round(np.random.uniform(22, 36, 100), 1),
    "ALT": np.random.randint(25, 90, 100),
    "AST": np.random.randint(20, 80, 100),
    "Triglycerides": np.random.randint(120, 300, 100),
    "Cholesterol": np.random.randint(180, 320, 100),
    "Glucose": np.random.randint(85, 150, 100),
    "FattyLiver": np.random.randint(0, 2, 100)  # 0 = No, 1 = Yes
}
df = pd.DataFrame(data)
df.head(5)

,Age,BMI,ALT,AST,Triglycerides,Cholesterol,Glucose,FattyLiver
0,62,28.3,55,60,132,296,127,0
1,37,34.5,42,41,250,289,142,1
2,33,27.3,89,78,196,202,110,1
3,34,29.5,85,36,216,209,117,0
4,36,31.1,42,48,216,198,118,0


In [ ]:
avg_second_col = df.iloc[:, 1].mean()
print(avg_second_col)

28.525000000000006


In [ ]:
avg_3rd_4th = df.iloc[:5, 2:4].mean()
print(avg_3rd_4th)

ALT    62.6
AST    52.6
dtype: float64


In [ ]:
avg_combined = df.iloc[:5, 2:4].values.mean()
print(avg_combined)

57.6


In [ ]:
row_wise_sum = df.sum(axis=1)
print(row_wise_sum)

0     760.3
1     836.5
2     736.3
3     726.5
4     689.1
      ...  
95    724.6
96    773.4
97    688.7
98    727.4
99    760.4
Length: 100, dtype: float64


In [ ]:
row_wise_avg = df.mean(axis=1)
max_avg = row_wise_avg.max()

print(max_avg)

112.6125
